{% set name = "azure-mgmt-core" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 380ae3dfa3639f4a5c246a7db7ed2d08374e88230fd0da3eb899f7c11e5c441a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - azure-core <2.0.0,>=1.26.2

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.core

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE.md
  summary: Microsoft Azure Management Core Library for Python.
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-mgmt-core

extra:
  recipe-maintainers:
    - tim-werner
    - xylar
